name: Events Demo 1
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'feature/**'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy project
        run: echo "Deploying..."
